version: '3'
services: # define containers
  pokemon: # this name can be anything
    build:
      dockerfile: Dockerfile # dockerfile name
      context: ./ # dockerfile path
    volumes: # volumes configuration for live code-editing
      - /app/node_modules # docker /app/node_modules (not needed to map)
      - ./:/app # mapping all files in local
    ports:
      - '3001:3001' # port MAPPING
    stdin_open: true # this option is needed for start, close React app
